### ISSUE TITLE
The Terracotta server was in state STOPPED and was expected to reach one of the states

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/angela#41] opened 2020-04-14 20:05 UTC
Since the new Angela version with the "stop" change, some builds are randomly failing.

Example: https://dev.azure.com/TerracottaCI/terracotta/_build/results?buildId=4133&view=logs&j=feb91b3b-c1e7-5841-2b9b-cf68bbf6cff5&t=dae69362-8928-54a2-bd53-da7b3ca8e43a

```
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 136.111 s <<< FAILURE! - in org.terracotta.dynamic_config.system_tests.diagnostic.SetCommand1x2IT
[ERROR] testCluster_setOffheap(org.terracotta.dynamic_config.system_tests.diagnostic.SetCommand1x2IT)  Time elapsed: 10.659 s  <<< ERROR!
class org.apache.ignite.IgniteException: Remote job threw user exception (override or implement ComputeTask.result(..) method if you would like to have automatic failover for this exception): Failed to execute job due to unexpected runtime exception [jobId=38c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.terracotta.angela.client.Tsa$$Lambda$287/0x000000010048ac40, dep=GridDeployment [ts=1586889327600, depMode=SHARED, clsLdr=jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a, clsLdrId=24743c97171-787e621d-ae89-4c50-9ac9-adc1bd9dbf21, userVer=0, loc=true, sampleClsName=org.terracotta.angela.common.util.IgniteCommonHelper, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=org.terracotta.angela.client.Tsa$$Lambda$287/0x000000010048ac40, sesId=28c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38, startTime=1586889333812, endTime=9223372036854775807, taskNodeId=d228f81b-7e8a-48c6-8e6f-7b6fae784e38, clsLdr=jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=null, subjId=d228f81b-7e8a-48c6-8e6f-7b6fae784e38, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=380656297]], execName=null], jobId=38c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38], err=The Terracotta server was in state STOPPED and was expected to reach one of the states: STARTED_AS_ACTIVE STARTED_AS_PASSIVE STARTED_IN_DIAGNOSTIC_MODE START_SUSPENDED but died before reaching it.]
	at org.apache.ignite.compute.ComputeTaskAdapter.result(ComputeTaskAdapter.java:102)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1053)
	at org.apache.ignite.internal.processors.task.GridTaskWorker$5.apply(GridTaskWorker.java:1046)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6852)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.result(GridTaskWorker.java:1046)
	at org.apache.ignite.internal.processors.task.GridTaskWorker.onResponse(GridTaskWorker.java:864)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor.processJobExecuteResponse(GridTaskProcessor.java:1081)
	at org.apache.ignite.internal.processors.task.GridTaskProcessor$JobMessageListener.onMessage(GridTaskProcessor.java:1316)
	at org.apache.ignite.internal.managers.communication.GridIoManager.invokeListener(GridIoManager.java:1569)
	at org.apache.ignite.internal.managers.communication.GridIoManager.processRegularMessage0(GridIoManager.java:1197)
	at org.apache.ignite.internal.managers.communication.GridIoManager.access$4200(GridIoManager.java:127)
	at org.apache.ignite.internal.managers.communication.GridIoManager$9.run(GridIoManager.java:1093)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: class org.apache.ignite.compute.ComputeUserUndeclaredException: Failed to execute job due to unexpected runtime exception [jobId=38c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38, ses=GridJobSessionImpl [ses=GridTaskSessionImpl [taskName=org.terracotta.angela.client.Tsa$$Lambda$287/0x000000010048ac40, dep=GridDeployment [ts=1586889327600, depMode=SHARED, clsLdr=jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a, clsLdrId=24743c97171-787e621d-ae89-4c50-9ac9-adc1bd9dbf21, userVer=0, loc=true, sampleClsName=org.terracotta.angela.common.util.IgniteCommonHelper, pendingUndeploy=false, undeployed=false, usage=1], taskClsName=org.terracotta.angela.client.Tsa$$Lambda$287/0x000000010048ac40, sesId=28c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38, startTime=1586889333812, endTime=9223372036854775807, taskNodeId=d228f81b-7e8a-48c6-8e6f-7b6fae784e38, clsLdr=jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a, closed=false, cpSpi=null, failSpi=null, loadSpi=null, usage=1, fullSup=false, internal=false, topPred=null, subjId=d228f81b-7e8a-48c6-8e6f-7b6fae784e38, mapFut=IgniteFuture [orig=GridFutureAdapter [ignoreInterrupts=false, state=INIT, res=null, hash=380656297]], execName=null], jobId=38c43c97171-d228f81b-7e8a-48c6-8e6f-7b6fae784e38], err=The Terracotta server was in state STOPPED and was expected to reach one of the states: STARTED_AS_ACTIVE STARTED_AS_PASSIVE STARTED_IN_DIAGNOSTIC_MODE START_SUSPENDED but died before reaching it.]
	at org.apache.ignite.internal.processors.job.GridJobWorker.handleThrowable(GridJobWorker.java:689)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:621)
	at org.apache.ignite.internal.processors.job.GridJobWorker.body(GridJobWorker.java:491)
	at org.apache.ignite.internal.util.worker.GridWorker.run(GridWorker.java:120)
	at org.apache.ignite.internal.processors.job.GridJobProcessor.processJobExecuteRequest(GridJobProcessor.java:1191)
	at org.apache.ignite.internal.processors.job.GridJobProcessor$JobExecutionListener.onMessage(GridJobProcessor.java:1923)
	... 7 more
Caused by: java.lang.RuntimeException: The Terracotta server was in state STOPPED and was expected to reach one of the states: STARTED_AS_ACTIVE STARTED_AS_PASSIVE STARTED_IN_DIAGNOSTIC_MODE START_SUSPENDED but died before reaching it.
	at org.terracotta.angela.common.TerracottaServerInstance.waitForState(TerracottaServerInstance.java:161)
	at org.terracotta.angela.agent.AgentController.waitForTsaInState(AgentController.java:295)
	at org.terracotta.angela.client.Tsa.lambda$start$7b0bf020$1(Tsa.java:250)
	at org.apache.ignite.internal.processors.closure.GridClosureProcessor$C4.execute(GridClosureProcessor.java:1944)
	at org.apache.ignite.internal.processors.job.GridJobWorker$2.call(GridJobWorker.java:568)
	at org.apache.ignite.internal.util.IgniteUtils.wrapThreadLoader(IgniteUtils.java:6820)
	at org.apache.ignite.internal.processors.job.GridJobWorker.execute0(GridJobWorker.java:562)
	... 11 more
```

**Comment by mathieucarbou** [comment] 2020-04-15 05:22
Note: this issue happened a few time but not on the subsequent builds... It is not always reproducible.

**Comment by saurabhagas** [comment] 2020-04-23 19:07
This Exception can be seen for a lot of reasons. The build link has vanished too. Closing this issue for lack of information. Can be reopened if the issue is seen again.

**Closed by saurabhagas** 2020-04-23 19:07 UTC
